---

###############################################################################
# Valid defaults
###############################################################################

# OpenNebula repository version
opennebula_repository_version: '6.8.0'

# Repository of the OpenNebula packages
opennebula_repository_base: 'https://downloads.opennebula.io/repo/{{ opennebula_repository_version }}'

# Enable GPG check for the packages
opennebula_repository_gpgcheck: yes

# Enable GPG check for the repos (RHEL/CentOS only)
opennebula_repository_repo_gpgcheck: yes
