---

- name: Install OpenNebula node package
  apt:
    name: opennebula-node
    state: latest
  register: apt_result
  until: apt_result | succeeded
  retries: 3
  delay: 10

# RHEL / CentOS compatibility
- name: Create /usr/libexec
  file:
    path: '/usr/libexec'
    state: directory

- name: Create symlink /usr/libexec/qemu-kvm
  file:
    src: /usr/bin/qemu-system-x86_64
    dest: /usr/libexec/qemu-kvm
    state: link
