---

- name: Set net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "{{ iptables_ip_forward_enabled | int }}"
    state: present
    sysctl_file: /etc/sysctl.d/ip_forward.conf
    reload: yes

- include_tasks: '{{ ansible_os_family }}.yml'
  when: iptables_manage_persistent

- include_tasks: rules.yml

- name: Restart iptables service
  service:
    name: iptables
    state: restarted
